### ISSUE TITLE
Guaranteed representation?

### ISSUE THREAD

**Issue by venkatarun95** [marcianx/bitvec-rs#2]
Is there a guaranteed representation for how bits are packed in `u8`. I.e. does a lower index correspond to the LSB or the MSB. Having a guarantee seems to be in line with this crate's guaranteed `[u8]` representation. It also makes `from_bytes` and `as_bytes` more meaningful. 

If you indeed want to (or already have) commit to a representation, it would be nice to add that to the root-level documentation of the crate

**Comment by marcianx** [comment]
Yes, it's guaranteed to be LSB 0, thanks for asking! I'll update the README.

**Comment by marcianx** [comment]
The README's been updated. I don't think there's any reason to push out another crate version. Please let me know if there's a strong reason to do so. Thanks again

**Comment by venkatarun95** [comment]
Thanks for taking care of this! Does it make sense to update the documentation as well?

**Comment by marcianx** [comment]
Ah, yes, good point. Done.
